export const SIDEBAR_ITEMS = [
  "Home",
  "Notifications",
  "Bookmarks",
  "Settings",
  "Profile",
];

export const FEED_POSTS = [
  {
    author: "marlo",
    handle: "@marlo",
    timeAgo: "2d",
    text: "if Mirag3 is dead then why is my engagement here 10x better than on any other platform",
    replies: 37,
    recasts: 15,
    likes: 165,
  },
  {
    author: "trupty",
    handle: "@trupty",
    timeAgo: "2d",
    text: "beverage break\n\nlooks like work, but smells like a whole garden.\nrose, longan, saffron, red dates.\ni wish you could smell this",
    replies: 54,
    recasts: 22,
    likes: 242,
    media: true,
  },
  {
    author: "alex_dev",
    handle: "@alex_dev",
    timeAgo: "1h",
    text: "Just pushed my first frames project to production. The developer experience is honestly unmatched right now.",
    replies: 12,
    recasts: 5,
    likes: 89,
  },
  {
    author: "crypto_whale",
    handle: "@whale",
    timeAgo: "3h",
    text: "Patience is the only strategy that consistently works in this market. 📉📈",
    replies: 89,
    recasts: 45,
    likes: 512,
  },
  {
    author: "chef_mario",
    handle: "@mario_cooks",
    timeAgo: "5h",
    text: "Secret to a perfect carbonara: no cream, just egg yolks and pecorino romano. Trust the process.",
    replies: 22,
    recasts: 8,
    likes: 134,
    media: true,
  },
  {
    author: "sarah_j",
    handle: "@sarahj",
    timeAgo: "8h",
    text: "Morning run in Tokyo. The city is so quiet at 5 AM. 🗼",
    replies: 15,
    recasts: 3,
    likes: 92,
    media: true,
  },
  {
    author: "tech_insider",
    handle: "@insider",
    timeAgo: "12h",
    text: "Rumor has it a new protocol is launching next week built entirely on base. Stay tuned.",
    replies: 142,
    recasts: 67,
    likes: 890,
  },
  {
    author: "nature_lover",
    handle: "@greenlife",
    timeAgo: "1d",
    text: "Planting season is finally here! My balcony is about to turn into a jungle.",
    replies: 8,
    recasts: 2,
    likes: 45,
  },
  {
    author: "pixel_artist",
    handle: "@pixelart",
    timeAgo: "1d",
    text: "Finished my 365-day challenge. Here is the final piece. What do you think?",
    replies: 230,
    recasts: 112,
    likes: 1540,
    media: true,
  },
  {
    author: "zen_master",
    handle: "@zen",
    timeAgo: "1d",
    text: "Don't let the noise of others' opinions drown out your own inner voice.",
    replies: 45,
    recasts: 34,
    likes: 320,
  },
  {
    author: "backend_guy",
    handle: "@db_admin",
    timeAgo: "1d",
    text: "Why is production down? Oh wait, I forgot to run migrations again.",
    replies: 67,
    recasts: 21,
    likes: 198,
  },
  {
    author: "traveler_dan",
    handle: "@dan_t",
    timeAgo: "2d",
    text: "Exploring the hidden gems of Bali. This waterfall is absolutely breathtaking.",
    replies: 31,
    recasts: 14,
    likes: 276,
    media: true,
  },
  {
    author: "fitness_pro",
    handle: "@fit_life",
    timeAgo: "2d",
    text: "Consistency > Intensity. Show up every day even if it's just for 15 minutes.",
    replies: 19,
    recasts: 7,
    likes: 110,
  },
  {
    author: "bookworm",
    handle: "@reading_nook",
    timeAgo: "3d",
    text: "Just finished 'The Alchemist' for the 5th time. Still hits different.",
    replies: 42,
    recasts: 18,
    likes: 156,
  },
  {
    author: "ai_enthusiast",
    handle: "@ai_future",
    timeAgo: "3d",
    text: "The pace of AI development is terrifying and exciting at the same time.",
    replies: 104,
    recasts: 56,
    likes: 670,
  },
  {
    author: "coffee_addict",
    handle: "@brew_master",
    timeAgo: "4d",
    text: "Trying a new light roast from Ethiopia today. Notes of jasmine and lemon.",
    replies: 11,
    recasts: 4,
    likes: 83,
    media: true,
  },
  {
    author: "startup_founder",
    handle: "@build_in_public",
    timeAgo: "4d",
    text: "Failed fast. Pivoting the entire roadmap tomorrow. Let's go again.",
    replies: 55,
    recasts: 29,
    likes: 412,
  },
  {
    author: "gamer_tag",
    handle: "@pro_gamer",
    timeAgo: "5d",
    text: "Finally hit the top 100 on the global leaderboard! Hard work pays off.",
    replies: 78,
    recasts: 12,
    likes: 560,
    media: true,
  },
  {
    author: "history_buff",
    handle: "@past_facts",
    timeAgo: "6d",
    text: "Did you know that in 1912, a man survived the Titanic by drinking enough whiskey to stay warm?",
    replies: 92,
    recasts: 110,
    likes: 820,
  },
  {
    author: "minimalist",
    handle: "@lessismore",
    timeAgo: "1w",
    text: "Ownership is a trap. The less you have, the more freedom you feel.",
    replies: 28,
    recasts: 15,
    likes: 215,
  },
];

export const RIGHT_LINKS = ["Support", "Privacy", "Terms", "Developers"];

export const CHANNELS = [
  "/home",
  "/builders",
  "/design",
  "/monad",
  "/bcc",
  "/web3",
];

export const TRENDING_CASTS = [
  {
    author: "@nabila",
    text: "social apps feel better when discovery beats followers",
    stats: "498 likes | 58 recasts",
  },
];
